default_language_version:
  python: python
default_stages: [commit, push, manual]
repos:
  - repo: https://github.com/ambv/black
    rev: 22.6.0
    hooks:
      - id: black
        name: black
        entry: black
        require_serial: true
        types: [python]
        files: \.pyi?$

  - repo: https://github.com/asottile/pyupgrade
    rev: v2.34.0
    hooks:
      - id: pyupgrade
        args: ["--py36-plus"]

  - repo: https://github.com/asottile/blacken-docs
    rev: v1.12.1
    hooks:
      - id: blacken-docs
        additional_dependencies: [black]
        language: python

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-yaml
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-docstring-first
      - id: mixed-line-ending
      - id: detect-private-key
      - id: end-of-file-fixer
        exclude: docs/notebooks/
      - id: trailing-whitespace
        types: [text]
      - id: debug-statements
        name: Debug Statements (Python)
        description: Check for debugger imports and py37+ `breakpoint()` calls in python source.
        entry: debug-statement-hook
        language: python
        types: [python]

  - repo: https://gitlab.com/pycqa/flake8
    rev: "3.9.2"
    hooks:
      - id: flake8
        language: python

  - repo: https://github.com/asottile/reorder_python_imports
    rev: v3.3.0
    hooks:
      - id: reorder-python-imports
        entry: reorder-python-imports
        language: python
        types: [python]
        minimum_pre_commit_version: "0.15.0"
