default_language_version:
  python: python
default_stages: [commit, push, manual]
repos:
  - repo: https://github.com/ambv/black
    rev: 22.6.0
    hooks:
      - id: black
        name: black
        entry: black
        require_serial: true
        types: [python]
        files: \.pyi?$

  - repo: https://github.com/asottile/blacken-docs
    rev: v1.12.1
    hooks:
      - id: blacken-docs
        additional_dependencies: [black==19.3b0]
        language: python

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-yaml
        language: python
      - id: check-added-large-files
        language: python
      - id: fix-encoding-pragma
        language: python
      - id: check-docstring-first
        language: python
      - id: end-of-file-fixer
        language: python
        exclude: docs/notebooks/
      - id: trailing-whitespace
        language: python
        types: [text]
      - id: debug-statements
        name: Debug Statements (Python)
        description: Check for debugger imports and py37+ `breakpoint()` calls in python source.
        entry: debug-statement-hook
        language: python
        types: [python]

  - repo: https://gitlab.com/pycqa/flake8
    rev: "3.9.2"
    hooks:
      - id: flake8
        language: python

  - repo: https://github.com/asottile/reorder_python_imports
    rev: v3.3.0
    hooks:
      - id: reorder-python-imports
        name: Reorder python imports
        description: This hook reorders imports in python files.
        entry: reorder-python-imports
        language: python
        types: [python]
        minimum_pre_commit_version: "0.15.0"
